replicaCount: 1

image:
  repository: ghcr.io/neo4g/operator
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

leaderElect: true

nodeSelector: {}
tolerations: []
affinity: {}
